title: Shahnila Khan # Shahnila Khan (or website title) here
logo: "/images/S.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Business Analyst | Business Analysis Bootcamp Graduate | Analytical & Detail-Oriented Professional | Certified Pharmacy Technician
  <br><br>
  As a certified Pharmacy Technician at Walmart with a background in healthcare and a strong foundation in Business Analysis, I bring a unique blend of skills to the table. Recently, I completed a comprehensive Business Analyst boot camp at TripleTen, where I gained expertise in tools and techniques such as Tableau, Power BI, SQL, Microsoft Excel, Pivot Tables, and presentation skills.
<br>
I’m passionate about leveraging data to drive informed decisions and improve business outcomes. My experience in customer-focused roles has honed my problem-solving abilities and communication skills, which I’m eager to apply in a Business Analyst role.
<br>
I'm actively seeking opportunities in Business Analysis where I can contribute my skills and continue learning. If you have an opportunity or would like to connect, feel free to reach out. 
  <br><br>
  <a href="www.linkedin.com/in/shahnila-k-b0758b352/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
